name: Jetson Deployment

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  catkin_make:
    name: Build and Deploy Package
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Move Package
        run: cp -r ./ ~/catkin_ws/src/ares_autonomy

      - name: Build
        working-directory: ~/catkin_ws
        run: source /opt/ros/melodic/setup.bash && source ~/catkin_ws/devel/setup.bash && catkin_make -DCMAKE_BUILD_TYPE=Release -DCATKIN_WHITELIST_PACKAGES=""
        shell: bash

          
