name: 'Submodules Sync'
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Update References
        run: |
          git pull --recurse-submodules
          git submodule update --recursive --remote

      - name: Push Update
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'main'
          commit-message: 'Updated submodules.'
          name: OzU Rover GitHub Actions Initializer
          email: ozu-rover-github-actions@xreos.co
